name: Angular CD

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        working-directory: recipes-angular
        run: npm install

      - name: Build Angular
        working-directory: recipes-angular
        run: npm run build -- --configuration production

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: recipes-angular/dist